runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 300
service: t5-base-flex

runtime_config:
  python_version: 3

manual_scaling:
  instances: 3
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20
