apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zeroshot-t5
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
    spec:
      containers:
      - image: gcr.io/gft-bike-insurance/zeroshot-t5:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: '2'
            memory: 8192Mi
      serviceAccountName: 704608691211-compute@developer.gserviceaccount.com