apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeroshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeroshot
  template:
    metadata:
      labels:
        app: zeroshot
    spec:
      containers:
      - name: zeroshot
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/test-project-256613/zeroshot:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"